print("----------------------")
print("       ELTXCRY")
print("----------------------")
print("ALL OF YOUR DATA IS GONE")
print("You cant restore data !")
print("To restore data please contact me on RE:TALK : EletrixTimeLeVrai")
